fallback = ''

[matching]
'discord' = ''
'balena-etcher' = ''
'Chia Blockchain' = ''
'Steam' = ''
'vlc' = ''
'mpv' = ''
'org.qbittorrent.qBittorrent' = ''
'Thunderbird' = ''
'thunderbird' = ''
'Postman' = ''
'Insomnia' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'/Chromium/' = ''
'org.qutebrowser.qutebrowser' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-studio' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'/(?i)Github.*[Ff]irefox/' = ''
'/[fF]irefox/' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'vivaldi-stable' = ''
'/(vim|nvim|NVIM) ?\w*/' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'/cargo/' = ''
'/RUST/' = ''
'/rust/' = ''
'/python/' = ''
'Alacritty' = ''
'org.wezfurlong.wezterm' = ''
